%YAML:1.0
image_width: 320 
image_height: 240
camera_name: head_camera
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [277.191356, 0.0, 320.5,
         0.0, 277.191356, 240.5,
         0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ 0, 0, 0., 0.,0.]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  data: [277.191356, 0.0, 320.5, 0.0, 277.191356, 240.5, 0.0, 0.0, 1.0]
